import { test, expect } from '../../../tests/browser/fixtures'
import type { Locator } from '@playwright/test'

async function select(text: Locator) {
  await text.scrollIntoViewIfNeeded()
  return text.evaluate((el) => {
    const range = document.createRange()
    range.selectNodeContents(el)
    getSelection()!.removeAllRanges()
    getSelection()!.addRange(range)
    return el.textContent!
  })
}

test('long live response has selection-only clipping, deduplication and a left index drawer', async ({
  page,
}) => {
  await page.goto('/prototypes/tracing/')
  const chat = page.getByRole('complementary', { name: 'Research chat' })
  const reply = page.getByRole('region', { name: 'Folio message' })
  const action = page.getByRole('button', { name: 'Save to index', exact: true })
  await expect(action).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Keep', exact: true })).toHaveCount(0)
  await expect(reply.locator('strong').first()).toBeVisible()
  const passage = reply.locator('p').nth(7)
  const excerpt = await select(passage)
  await expect(action).toBeVisible()
  await page.screenshot({ path: test.info().outputPath('selection-desktop.png') })
  await action.click()
  await expect(action).toHaveCount(0)
  await select(passage)
  await action.click()
  const scroll = await chat.locator('.messages').evaluate((el) => el.scrollTop)
  await chat.getByRole('button', { name: 'INDEX', exact: true }).click()
  const index = page.getByRole('region', { name: 'Index', exact: true })
  await expect(index.locator('.clipping')).toHaveCount(1)
  await expect(index.locator('.excerpt')).toHaveText(excerpt)
  expect((await index.boundingBox())!.x).toBe(0)
  expect((await index.boundingBox())!.width).toBe(380)
  await page.screenshot({ path: test.info().outputPath('index-desktop.png') })
  await index.getByRole('button', { name: 'CHAT', exact: true }).click()
  await expect.poll(() => chat.locator('.messages').evaluate((el) => el.scrollTop)).toBeCloseTo(scroll, 0)
  await chat.getByRole('button', { name: 'INDEX', exact: true }).click()
  await index.locator('.excerpt').click()
  await expect(index.getByRole('region', { name: 'Saved conversation' })).toContainText(
    'The Gap You Kept Open',
  )
  await index.getByRole('button', { name: 'Open research chat' }).click()
  await expect(passage).toBeInViewport()
  await page.reload()
  await chat.getByRole('button', { name: 'INDEX', exact: true }).click()
  await expect(index.locator('.clipping')).toHaveCount(1)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: test.info().outputPath('index-mobile.png') })
  expect((await index.boundingBox())!.width).toBeLessThan(390)
})

test('essay selection is non-destructive, keyboard accessible and dismissible', async ({ page }) => {
  await page.goto('/prototypes/tracing/')
  await page.getByRole('button', { name: 'Close research chat' }).click()
  const essay = page.getByRole('article', { name: 'Sample essay' })
  const original = await essay.textContent()
  const excerpt = await select(essay.locator('p').first())
  const action = page.getByRole('button', { name: 'Save to index' })
  await expect(action).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(action).toHaveCount(0)
  await select(essay.locator('p').first())
  await expect(action).toBeVisible()
  await page.keyboard.press('Tab')
  await expect(action).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(essay).toHaveText(original!)
  await page.getByRole('button', { name: 'Open index', exact: true }).click()
  const index = page.getByRole('region', { name: 'Index', exact: true })
  await expect(index.locator('.excerpt')).toHaveText(excerpt)
  await expect(index).toContainText('01 / ESSAY')
  await index.locator('.excerpt').click()
  await expect(index).toContainText('ESSAY WHEN SAVED')
  await index.getByRole('button', { name: 'Back to essay' }).click()
  await expect(essay.locator('p').first()).toBeInViewport()
  await page.setViewportSize({ width: 390, height: 844 })
  await select(essay.locator('p').first())
  await expect(action).toBeVisible()
  const box = (await action.boundingBox())!
  expect(box.x).toBeGreaterThanOrEqual(0)
  expect(box.x + box.width).toBeLessThanOrEqual(390)
  await page.screenshot({ path: test.info().outputPath('selection-mobile.png') })
})

test('artifact rail is separate from research and index', async ({ page }) => {
  await page.goto('/prototypes/tracing/')
  const right = page.getByRole('complementary', { name: 'Graphic conversation' })
  await expect(right).toHaveCount(0)
  await page.getByRole('button', { name: 'Open graphic editing' }).click()
  await right.getByLabel('Graphic instruction').fill('Use small dots instead of a line.')
  await right.getByRole('button', { name: 'Note instruction' }).click()
  await expect(right).toContainText('Use small dots instead of a line.')
  await expect(page.getByRole('complementary', { name: 'Research chat' })).not.toContainText('Use small dots')
  await right.getByRole('button', { name: 'Close graphic conversation' }).click()
  await expect(right).toHaveCount(0)
})
