import { test, expect } from './fixtures'

for (const width of [1440, 390])
  test(`info keeps history and working restore beneath two actions at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/?qa=essay')
    const info = page.getByRole('region', { name: 'Story history' })
    const toggle = page.getByRole('button', { name: 'History', exact: true })
    await toggle.click()
    await expect(info.getByRole('heading', { name: 'HISTORY', exact: true })).toBeVisible()
    await expect(info).toContainText('No earlier versions yet')
    await expect(info.locator('.story-downloads button')).toHaveText(['Copy text', 'Download'])
    await expect(info.getByRole('checkbox')).toHaveCount(0)
    await info.getByRole('button', { name: 'Download', exact: true }).click()
    await expect(info.getByRole('button', { name: 'HTML', exact: true })).toBeVisible()
    await expect(info.getByRole('checkbox')).toBeVisible()
    await info.getByRole('button', { name: 'Download', exact: true }).click()
    await toggle.click()
    const paragraph = page.locator('[data-block-id] textarea.prose-input').first()
    const original = await paragraph.inputValue()
    await paragraph.fill('A revision we can safely reverse.')
    await toggle.click()
    const revision = info.locator('button.hover-row').first()
    await expect(revision).toBeVisible()
    const download = (await info.getByRole('button', { name: 'Download', exact: true }).boundingBox())!
    const heading = (await info.getByRole('heading', { name: 'HISTORY' }).boundingBox())!
    expect(heading.y).toBeGreaterThan(download.y + download.height)
    await page.screenshot({ path: test.info().outputPath(`info-history-${width}.png`), animations: 'disabled' })
    await revision.click()
    await expect(paragraph).toHaveValue(original)
    await toggle.click()
    await expect(info.locator('button.hover-row').first()).toContainText('Restored')
    await info.locator('button.hover-row').first().click()
    await expect(paragraph).toHaveValue('A revision we can safely reverse.')
  })
